apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres.yaml

namespace: air-quality-api-cnpe-dev

images:
  - name: air-quality-api
    newName: 918780499156.dkr.ecr.eu-west-1.amazonaws.com/cnpe/air-quality-api
    newTag: "02"

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: air-quality-api
    path: httproute-host.patch.yaml
  - path: image-pull-policy.patch.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: air-quality-api
    path: configmap-db.patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: air-quality-api
    path: deployment-db.patch.yaml
