apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/weather-api/overlays/local
  - ../../apps/air-quality-api/overlays/local
  - ../../apps/map-api/overlays/local
