apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: air-quality-api
  labels:
    app: air-quality-api
spec:
  ingressClassName: nginx
  rules:
    - host: air-quality-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: air-quality-api
                port:
                  name: http
