apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonAnnotations:
  app.kubernetes.io/source-repo: https://github.com/amohsenter09-github/air-quality-api
  app.kubernetes.io/version: "01"
