apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres.yaml

namespace: map-api-cnpe-dev

images:
  - name: map-api
    newName: rg.fr-par.scw.cloud/cnpe/map-api
    newTag: "02"

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: map-api
    path: httproute-host.patch.yaml
  - path: image-pull-policy.patch.yaml
  - target:
      version: v1
      kind: ConfigMap
      name: map-api
    path: configmap-db.patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: map-api
    path: deployment-db.patch.yaml
